# Generated by Django 3.2.7 on 2021-09-26 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_alter_city_cnamecity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cavatar',
            field=models.ImageField(blank=True, default=None, max_length=255, null=True, upload_to=''),
        ),
    ]
