# Generated by Django 3.2.7 on 2021-09-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0003_alter_user_cavatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cavatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
