# Generated by Django 3.2.7 on 2021-09-28 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0004_alter_user_cavatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='nidCountry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clases.country'),
        ),
        migrations.AlterField(
            model_name='detail_category',
            name='nidCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clases.category'),
        ),
        migrations.AlterField(
            model_name='detail_category',
            name='nidUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='detail_game',
            name='nidGame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clases.game'),
        ),
        migrations.AlterField(
            model_name='detail_game',
            name='nidUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='detail_user',
            name='nidCharacteristic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clases.characteristic_user'),
        ),
        migrations.AlterField(
            model_name='detail_user',
            name='nidUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='nidCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clases.category'),
        ),
        migrations.AlterField(
            model_name='match',
            name='nidUser1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='nidUser2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='nidRoom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clases.room'),
        ),
        migrations.AlterField(
            model_name='message',
            name='nidUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='cidMatch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clases.match'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cavatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nidCity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clases.city'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nidGender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clases.gender'),
        ),
    ]
