# Generated by Django 3.2.7 on 2021-09-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0005_auto_20210927_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cavatar',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
