# Generated by Django 3.2.7 on 2021-09-28 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0006_alter_user_cavatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cavatar',
            field=models.ImageField(blank=True, default=None, max_length=255, null=True, upload_to='images/'),
        ),
    ]
