# Generated by Django 3.2.7 on 2021-10-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0007_alter_user_cavatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cavatar',
            field=models.ImageField(blank='', default='', upload_to='images/'),
        ),
    ]
